const PAGINATE_USERS = 'PAGINATE_USERS';
const SHOW_USER  = 'SHOW_USER';
const CREATE_USER  = 'CREATE_USER';
const UPDATE_USER  = 'UPDATE_USER';
const UPDATE_USER_PASSWORD  = 'UPDATE_USER_PASSWORD';
const UPDATE_USER_STATUS  = 'UPDATE_USER_STATUS';
const UPDATE_USER_AVATAR  = 'UPDATE_USER_AVATAR';
const DELETE_USER  = 'DELETE_USER';

export const PAGINATE_USERS_REQUESTED = `${PAGINATE_USERS}_REQUESTED`;
export const PAGINATE_USERS_SUCCEEDED = `${PAGINATE_USERS}_SUCCEEDED`;
export const PAGINATE_USERS_FAILED = `${PAGINATE_USERS}_FAILED`;

export const SHOW_USER_REQUESTED = `${SHOW_USER}_REQUESTED`;
export const SHOW_USER_SUCCEEDED = `${SHOW_USER}_SUCCEEDED`;
export const SHOW_USER_FAILED = `${SHOW_USER}_FAILED`;

export const CREATE_USER_REQUESTED = `${CREATE_USER}_REQUESTED`;
export const CREATE_USER_SUCCEEDED = `${CREATE_USER}_SUCCEEDED`;
export const CREATE_USER_FAILED = `${CREATE_USER}_FAILED`;

export const UPDATE_USER_REQUESTED = `${UPDATE_USER}_REQUESTED`;
export const UPDATE_USER_SUCCEEDED = `${UPDATE_USER}_SUCCEEDED`;
export const UPDATE_USER_FAILED = `${UPDATE_USER}_FAILED`;

export const UPDATE_USER_PASSWORD_REQUESTED = `${UPDATE_USER_PASSWORD}_REQUESTED`;
export const UPDATE_USER_PASSWORD_SUCCEEDED = `${UPDATE_USER_PASSWORD}_SUCCEEDED`;
export const UPDATE_USER_PASSWORD_FAILED = `${UPDATE_USER_PASSWORD}_FAILED`;

export const UPDATE_USER_STATUS_REQUESTED = `${UPDATE_USER_STATUS}_REQUESTED`;
export const UPDATE_USER_STATUS_SUCCEEDED = `${UPDATE_USER_STATUS}_SUCCEEDED`;
export const UPDATE_USER_STATUS_FAILED = `${UPDATE_USER_STATUS}_FAILED`;

export const UPDATE_USER_AVATAR_REQUESTED = `${UPDATE_USER_AVATAR}_REQUESTED`;
export const UPDATE_USER_AVATAR_SUCCEEDED = `${UPDATE_USER_AVATAR}_SUCCEEDED`;
export const UPDATE_USER_AVATAR_FAILED = `${UPDATE_USER_AVATAR}_FAILED`;

export const DELETE_USER_REQUESTED = `${DELETE_USER}_REQUESTED`;
export const DELETE_USER_SUCCEEDED = `${DELETE_USER}_SUCCEEDED`;
export const DELETE_USER_FAILED = `${DELETE_USER}_FAILED`;
