const PAGINATE_ROLES = 'PAGINATE_ROLES';
const SHOW_ROLE = 'SHOW_ROLE';
const CREATE_ROLE = 'CREATE_ROLE';
const UPDATE_ROLE = 'UPDATE_ROLE';
const DELETE_ROLE = 'DELETE_ROLE';
const LINK_ROLE_WITH_MENUS = 'LINK_ROLE_WITH_MENUS';

export const PAGINATE_ROLES_REQUESTED = `${PAGINATE_ROLES}_REQUESTED`;
export const PAGINATE_ROLES_SUCCEEDED = `${PAGINATE_ROLES}_SUCCEEDED`;
export const PAGINATE_ROLES_FAILED = `${PAGINATE_ROLES}_FAILED`;
export const PAGINATE_ROLES_CLEARED = `${PAGINATE_ROLES}_CLEARED`;

export const SHOW_ROLE_REQUESTED = `${SHOW_ROLE}_REQUESTED`;
export const SHOW_ROLE_SUCCEEDED = `${SHOW_ROLE}_SUCCEEDED`;
export const SHOW_ROLE_FAILED = `${SHOW_ROLE}_FAILED`;

export const CREATE_ROLE_REQUESTED = `${CREATE_ROLE}_REQUESTED`;
export const CREATE_ROLE_SUCCEEDED = `${CREATE_ROLE}_SUCCEEDED`;
export const CREATE_ROLE_FAILED = `${CREATE_ROLE}_FAILED`;

export const UPDATE_ROLE_REQUESTED = `${UPDATE_ROLE}_REQUESTED`;
export const UPDATE_ROLE_SUCCEEDED = `${UPDATE_ROLE}_SUCCEEDED`;
export const UPDATE_ROLE_FAILED = `${UPDATE_ROLE}_FAILED`;

export const DELETE_ROLE_REQUESTED = `${DELETE_ROLE}_REQUESTED`;
export const DELETE_ROLE_SUCCEEDED = `${DELETE_ROLE}_SUCCEEDED`;
export const DELETE_ROLE_FAILED = `${DELETE_ROLE}_FAILED`;

export const LINK_ROLE_WITH_MENUS_REQUESTED = `${LINK_ROLE_WITH_MENUS}_REQUESTED`;
export const LINK_ROLE_WITH_MENUS_SUCCEEDED = `${LINK_ROLE_WITH_MENUS}_SUCCEEDED`;
export const LINK_ROLE_WITH_MENUS_FAILED = `${LINK_ROLE_WITH_MENUS}_FAILED`;
